import { PortfolioSummary, HoldingDisplay } from "@/types/holdings";

export const mockPortfolio: PortfolioSummary = {
  totalCost: 383200,
  totalGain: 70050,
  totalGainPercent: 18.3,
  currentValue: 165000,
  totalDividends: 3606,
  dividendYield: 19.2,
  activePositions: 1,
  soldPositions: 1,
};

export const mockHoldings: HoldingDisplay[] = [
  {
    id: "1",
    name: "Salmar ASA",
    ticker: "SALM",
    description: "Et av verdens største og mest effektive lakseoppdrettsselskaper",
    isSold: true,
    returnPercent: 23.6,
    ownershipType: "Privat",
    ownerName: "Nitram Invest",
    broker: "Sparebank1 Markets",
    purchaseDate: "2025-08-08",
    saleDate: "2025-11-04",
    quantity: 0,
    avgPrice: 466,
    salePrice: 288250,
    totalCost: 233200,
    saleValue: 288250,
    realizedGain: 55050,
  },
  {
    id: "2",
    name: "Noram Drilling",
    ticker: "NODL",
    description: "Norsk boreselskap som leverer borerigg-tjenester til olje- og gassindustrien",
    isSold: false,
    returnPercent: 10.0,
    ownershipType: "Privat",
    ownerName: "Martin Moe",
    broker: "DNB",
    purchaseDate: "2025-01-15",
    quantity: 6000,
    avgPrice: 25,
    currentPrice: 28,
    lowPrice: 4.11,
    highPrice: 10.49,
    totalCost: 150000,
    currentValue: 165000,
    unrealizedGain: 15000,
    dividends: 3606,
    totalReturn: 12.4,
  },
];
